### ISSUE TITLE
Strange behavior of \newluatexattribute and \newskip

### ISSUE THREAD

**Issue by qinglee** [lualatex/luatexbase#20]
After running the following example:

    \input luatexbase.sty

    \newluatexattribute\testattr

    \newskip\testskip
    \testskip=1pt plus 100pt\relax

    \showthe\testskip

    \bye

I get

    \testskip=\skip256

    > 1.0pt plus 100.0pt minus 0.00002pt.
    l.10     \showthe\testskip

Please note that there is a strange  shrink component `minus 0.00002pt`. After removing `\newluatexattribute\testattr`, there will be a correct result:

    \testskip=\skip256
    
    > 1.0pt plus 100.0pt.
    l.9     \showthe\testskip

My LuaTeX is

    This is LuaTeX, Version beta-0.79.1 (TeX Live 2014/W32TeX) (rev 4971)  (format=luatex 2015.1.7)

**Comment by eroux** [comment]
This bug is extremely strange and, though I managed to find a workaround, this might be a dangerous bug in LuaTeX... Sadly, I don't manage to simplify it enough to make something readable by LuaTeX maintener (who are not interested in reading luatexbase code, which is too LaTeXish). I'll see what I can do later, but @qinglee can you please test this commit and tell me if it works for you?

**Comment by qinglee** [comment]
It works fine here. But this is still some kind of weird.

BTW, assignment of `\allocationnumber` should be terminated by a space or `\relax`, say

    diff --git a/luatexbase-attr.dtx b/luatexbase-attr.dtx
    index 528bdaf..8d58d68 100644
    --- a/luatexbase-attr.dtx
    +++ b/luatexbase-attr.dtx
    @@ -301,7 +301,7 @@ See the aforementioned source file(s) for copyright and licensing information.
       \begingroup\escapechar\m@ne \expandafter\expandafter\expandafter
       \endgroup                   \expandafter\expandafter\expandafter
       \allocationnumber           \luatexbase@directlua{tex.write(
    -    luatexbase.new_attribute("\luatexluaescapestring{\string#1}", true))}%
    +    luatexbase.new_attribute("\luatexluaescapestring{\string#1}", true))}\relax%
       \ifnum\allocationnumber>\m@ne
         \global\luatexattributedef#1=\allocationnumber
         \wlog{\string#1=\string\luatexattribute\the\allocationnumber}%

Otherwise, it will expand `\ifnum`  firstly and the testing is always invalid.

**Comment by eroux** [comment]
Thanx, could you please make a pull request for this?

Also, what kind of other weirdness do you experiment? There is certainly still a bug hidden somewhere, whether in LuaTeX or in luatexbase, it would be good to catch it...

**Comment by qinglee** [comment]
Sorry, I know little about git. So you can use this patch directly.

I find the MWE is

    \attribute0=-"7FFFFFFF\relax
    \immediate\write-1{Anything}
    \immediate\write-1{Anything}
    \skip0=1pt plus 100pt\relax
    \showthe\skip0

    \bye

**Comment by eroux** [comment]
Thanks a lot @qinglee , i reported it [here](http://tracker.luatex.org/view.php?id=923)

**Comment by eroux** [comment]
closing, as it is not a luatexbase bug

**Comment by eroux** [comment]
FYI, it has apparently been fixed by [this commit](https://foundry.supelec.fr/scm/viewvc.php/?root=luatex&view=rev&revision=5152)
