### ISSUE TITLE
Allocation macros in latex 2015/01/01

### ISSUE THREAD

**Issue by davidcarlisle** [lualatex/luatexbase#21]
The 2015 latex release has started the process of integrating
support for engines beyond classic TeX.

In particular a new register allocation scheme is implemented that
uses extended allocation ranges with support for the ranges suitable
for etex, xetex and luatex.

This scheme not only supports the extended ranges but it is intended
to allow new allocation types without each register needing to define
a new allocation macro, currently this is just used for \newmarks
(previously in etex.sty) and \newXeTeXintercharclass (previously in
xetex.ini).

So by default a latex 2015/01/01 lualatex format has luatex-specific
allocation macros defined, however after loading luatexbase (usually
from fontspec or luaotfload) these macros are over-written firstly
with the etex.sty allocation scheme then this is further modified for
luatex. This breaks the new \extrafloats mechanism and introduces
incompatibilities between lualatex and pdflatex/xelatex.

Here I propose to not load etex.sty on new latex releases.
One could go further and make more use of the \e@alloc allocation
scheme (for catcode tables, attribute etc) but I don't suggest that
initially, and there would be issues to be decided on the best way to
provide the lua interface if that were done. Here I just suggest some
minimal changes to allow the new latex 2015 features to be used for
classic tex registers such as boxes and lengths.

We'd like to ask for this fix so that users can get an immediate
benefit: we can then have a more nuanced discussion about the
provision made by the LaTeX kernel and the resulting interaction with
third-party packages. Hopefully with a view to having standard
allocations for luatex in the format kernel in a future release.

Most (but not all) of the dependency on etex.sty comes from
luatex.sty. I have previously suggested that that package
should not load etex.sty, but even if luatex.sty were changed there
would still be a dependency on etex.sty via luatexbase-regs.

Here I suggest luatex.sty is not loaded on newer latex releases. As
the register allocation scheme doesn't need to be defined for luatex,
the remaining parts of luatex.sty (catcodetable and attribute
handling) already overlap the luatex-base features as noted in
the comments in luatexbase-attr. If it is not loaded a minimal
compatibility layer is suggested. (Perhaps more of the catcode table
handling should be covered: something to discuss)

Consider this test file

```
\documentclass{article}

\def\lshow#1{\typeout{^^J\string#1->\meaning#1^^J}}

\lshow\newbox

\usepackage{luaotfload}

\lshow\newbox
\lshow\newattribute
\lshow\newcatcodetable
\newluatexcatcodetable\zzz
\lshow\zzz

\newluatexattribute\kkk
\lshow\kkk

\begin{document}

\end{document}
```

It shows \newbox being redefined.

If the two patches suggested below are applied, then it should work in
an identical manner in a 2014 latex, but \newbox will not be redefined
in a 2015 latex.

```
*** luatexbase.orig	2015-06-14 18:21:19.098972500 +0100
--- luatexbase.sty	2015-06-14 23:48:01.045640400 +0100
***************
*** 74,80 ****
  \expandafter\ifx\csname RequirePackage\endcsname\relax
    \input luatex.sty
  \else
!   \RequirePackage{luatex}
  \fi
  \begingroup\expandafter\expandafter\expandafter\endgroup
  \expandafter\ifx\csname RequirePackage\endcsname\relax
--- 74,85 ----
  \expandafter\ifx\csname RequirePackage\endcsname\relax
    \input luatex.sty
  \else
!   \ifx\e@alloc\@undefined
!     \RequirePackage{luatex}
!   \else
!     % compatability with luatex.sty
!     \def\newcatcodetable{\newluatexcatcodetable}
!   \fi
  \fi
  \begingroup\expandafter\expandafter\expandafter\endgroup
  \expandafter\ifx\csname RequirePackage\endcsname\relax
***************
*** 89,95 ****
--- 94,102 ----
    \RequirePackage{luatexbase-compat}
    \RequirePackage{luatexbase-modutils}
    \RequirePackage{luatexbase-loader}
+ \ifx\e@alloc\@undefined
    \RequirePackage{luatexbase-regs}
+ \fi
    \RequirePackage{luatexbase-attr}
    \RequirePackage{luatexbase-cctb}
    \RequirePackage{luatexbase-mcb}
```

and

```
*** luatexbase-attr.orig	2015-06-14 18:43:34.555593200 +0100
--- luatexbase-attr.sty	2015-06-14 23:49:46.212816000 +0100
***************
*** 82,88 ****
    \input luatex.sty
  \else
    \RequirePackage{luatexbase-modutils}
!   \RequirePackage{luatex}
  \fi
  \luatexbase@ensure@primitive{luaescapestring}
  \luatexbase@ensure@primitive{attributedef}
--- 82,96 ----
    \input luatex.sty
  \else
    \RequirePackage{luatexbase-modutils}
!   \ifx\e@alloc\@undefined
!     \RequirePackage{luatex}
!   \else
!     % compatability with luatex.sty
!     \def\newattribute{\newluatexattribute}
!     % Just needed for the tests in attr.lua
!     \newcount\LuT@AllocAttribute
!     \LuT@AllocAttribute=-1
!   \fi
  \fi
  \luatexbase@ensure@primitive{luaescapestring}
  \luatexbase@ensure@primitive{attributedef}
```

Note here I have just edited the .sty files directly, if you are
considering accepting the changes I could edit the documented sources
and generate a proper pull request.

**Comment by eroux** [comment]
David, Thanks a lot for your work on LaTeX 2015 and your concern about this, this is very welcome! 

Sadly, the situation is a bit more intricate, and has proven unsolvable for years... luatex.sty is loaded by pdftexcmds.sty, which is loaded by hyperref. So as hyperref is loaded in almost all cases, luatex.sty will be loaded in almost all cases. And if we don't load luatex.sty then use dirty tricks to make it compatible with luaotfload (it is not), this means that people will have to choose between fontspec and hyperref, which seems quite difficult... I've tried to settle the situation with Heiko for years now (5 or 6 maybe), but I never managed to get any answer from him. Maybe you could give it a try, if he sees a famous name, he might answer... 

About conditional loading of luatex-regs, sure, that sounds good.

Thank you!

**Comment by josephwright** [comment]
@eroux I think there must have been some change somewhere. For me, with example
```latex
\listfiles
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\end{document}
```
I get
```
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
hyperref.sty    2012/11/06 v6.83m Hypertext links for LaTeX
hobsub-hyperref.sty    2012/05/28 v1.13 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2012/05/28 v1.13 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2012/05/28 v1.13 Construct package bundles (HO)
infwarerr.sty    2010/04/08 v1.3 Providing info/warning/error messages (HO)
 ltxcmds.sty    2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
  ifvtex.sty    2010/03/01 v1.5 Detect VTeX and its facilities (HO)
 intcalc.sty    2007/09/27 v1.1 Expandable calculations with integers (HO)
   ifpdf.sty    2011/01/30 v2.3 Provides the ifpdf switch (HO)
etexcmds.sty    2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2012/04/25 v1.16 Key value parser (HO)
kvdefinekeys.sty    2011/04/07 v1.3 Define keys (HO)
luatex-loader.sty    2010/03/09 v0.4 Lua module loader (HO)
pdftexcmds.sty    2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2011/11/25 v1.13 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2012/04/08 v1.3 Expandable calculations on big integers (HO)
  bitset.sty    2011/01/30 v1.1 Handle bit-vector datatype (HO)
uniquecounter.sty    2011/01/30 v1.2 Provide unlimited unique counter (HO)
letltxmacro.sty    2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
 hopatch.sty    2012/05/28 v1.2 Wrapper for package hooks (HO)
xcolor-patch.sty    2011/01/30 xcolor patch
atveryend.sty    2011/06/30 v1.8 Hooks at the very end of document (HO)
atbegshi.sty    2011/10/05 v1.16 At begin shipout hook (HO)
refcount.sty    2011/10/16 v3.4 Data extraction from label references (HO)
 hycolor.sty    2011/01/30 v1.7 Color options for hyperref/bookmark (HO)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 auxhook.sty    2011/03/04 v1.3 Hooks for auxiliary files (HO)
kvoptions.sty    2011/06/30 v3.11 Key value format for package options (HO)
  pd1enc.def    2012/11/06 v6.83m Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 hpdftex.def    2012/11/06 v6.83m Hyperref driver for pdfTeX
rerunfilecheck.sty    2011/04/15 v1.7 Rerun checks for auxiliary files (HO)
 nameref.sty    2012/10/27 v2.43 Cross-referencing by name of section
gettitlestring.sty    2010/12/03 v1.4 Cleanup title references (HO)
 ***********
```
with no loading of the `luatex` package. I'm not sure where the change has been made compared to what you've seen: I'll check back on my home machine later (I've got TL'12-Tl'15 there).

**Comment by josephwright** [comment]
Worth emphasising the point from @davidcarlisle 
> we can then have a more nuanced discussion about the
provision made by the LaTeX kernel and the resulting interaction with
third-party packages. Hopefully with a view to having standard
allocations for luatex in the format kernel in a future release.

Hopefully that can happen relatively quickly (depending on technical issues and views of various parties), and we can move toward having the kernel cover most (all?) of this directly.

**Comment by davidcarlisle** [comment]
I've pinged Heiko already so hopefully he'll comment here, but as I indicated,  in the medium term (say tl2016) it would be good to have all these allocations in the format. Allocation macros really should be in the format as otherwise the kind of incompatibilities we see now between etex.sty/luatex.sty/luatexbase.sty are inevitable. One could reasonably argue that the core latex format code ought to have acknowledged the extended texs earlier (sometime last century in the case of etex:-) but we are where we are but hopefully we can get the format on a more documentable footing without breaking too much even if there are some edge cases that require small document changes..


Certainly before any code changes we will need some good test files (with and without hyperref etc)

**Comment by eroux** [comment]
@davidcarlisle this would be really a great news! I still have TeXLive 2014, the change might have appeared afterwards... 

@josephwright I'm all for it! For me the sooner the better, this means less maintainance for me, less trouble dealing with Heiko's packages, etc.!

**Comment by josephwright** [comment]
@eroux  I'm hopeful. The work on TL'15 (or rather this year's LaTeX kernel release) means we are already in a much better place for this than was previously the case. There are some discussions to be had but the issues you raise are a good reason the team should pick this up.

**Comment by eroux** [comment]
Sorry, I've just realize I had forgotten this... Days are super-busy this week, do you think you could provide a Github pull request that I could merge? Or a git patch with the modifications from the initial comment?

**Comment by davidcarlisle** [comment]
On 16 June 2015 at 13:03, Elie Roux <notifications@github.com> wrote:

> Sorry, I've just realize I had forgotten this... Days are super-busy this
> week, do you think you could provide a Github pull request that I could
> merge? Or a git patch with the modifications from the initial comment?
>
> —
>



I forked the repository with the intention of doing that, however before
suggesting that you really make the change I think I want to make a few
more test files to better answer the question about what exactly would
change for documents using hyperref or direct;y loading luatex.sty etc.

Sadly didn't have any time yesterday, will report back later.

Also as Joseph and I commented longer term it would be good to have more of
this in
the format so another possibility would be to not make a change now and
then wait
until we agree that. Need the tests really to check how compatible the
suggested change is.

**Comment by eroux** [comment]
Ok, I let you decide what's best, I'll be ready to push the green button to merge a pull request if any! :)

**Comment by josephwright** [comment]
@davidcarlisle  Close?

**Comment by davidcarlisle** [comment]
yes, closing
