### ISSUE TITLE
Unexpected behavior with Unicode characters in \PackageWarningNoLine 

### ISSUE THREAD

**Issue by niruvt** [lualatex/luatexbase#22]
This is my code:

```latex
\documentclass{article}
\begin{filecontents}[overwrite]{quack.sty}
\ProvidesPackage{quack}[2021/11/30 v0.1 quack quack]
\newcommand{\quack}{%
  \PackageWarningNoLine{quack}{%
    ककाकिकी खखाखिखी गगागिगी घघाघिघी ङङाङिङी\MessageBreak
    चचाचिची छछाछिछी जजाजिजी झझाझिझी ञञाञिञी\MessageBreak
    टटाटिटी ठठाठिठी डडाडिडी ढढाढिढी णणाणिणी%
  }%
}
\end{filecontents}
\usepackage{quack}

\begin{document}
\quack
\end{document}
```

Only with `xelatex` I get the warning message printed correctly like this:

```
This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021)

Package quack Warning: ककाकिकी खखाखिखी गगागिगी घघाघिघी ङङाङिङी
(quack)                चचाचिची छछाछिछी जजाजिजी झझाझिझी ञञाञिञी
(quack)                टटाटिटी ठठाठिठी डडाडिडी ढढाढिढी णणाणिणी.
```

With `lualatex-dev` I get:

```
This is LuaHBTeX, Version 1.13.2 (TeX Live 2021)

Package quack Warning: ककाकिकी खखाखिखी गगा
गिगी घघाघिघी ङङाङिङी
(quack)                चचाचिची छछाछिछी जजा
जिजी झझाझिझी ञञाञिञी
(quack)                टटाटिटी ठठाठिठी डडा
डिडी ढढाढिढी णणाणिणी.
```

It's wrong with `pdflatex` too:

```
This is pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021)

Package quack Warning: ककाकिकी खखाखिखी गगाग
िगी घघाघिघी ङङाङिङी
(quack)                चचाचिची छछाछिछी जजाज
िजी झझाझिझी ञञाञिञी
(quack)                टटाटिटी ठठाठिठी डडाड
िडी ढढाढिढी णणाणिणी.
```

**Comment by u-fischer** [comment]
you will have to enlarge the line length. pdflatex and lualatex count in bytes. With e.g. `max_print_line=300` I get 

~~~~
Package quack Warning: गगागिगी घघाघिघी ङङाङिङी
(quack)                चचाचिची छछाछिछी जजाजिजी झझाझिझी ञञाञिञी
(quack)                टटाटिटी ठठाठिठी डडाडिडी ढढाढिढी णणाणिणी.
~~~~

**Comment by niruvt** [comment]
@u-fischer Where do I set it? In the .tex file, the .sty file or my shell? How is it handled correctly in xelatex?

**Comment by u-fischer** [comment]
If you have texlive in your texmf.cnf, miktex has .ini files for this. And the behaviour is not incorrect: There are various ways to count the length of a string, and counting by bytes is quite valid (and for pdflatex which has no notion of utf8 it is certainly the only sensible one).

**Comment by niruvt** [comment]
Okay.

I want to generate such a warning with my package. As I don't have access to people's .cnf or .ini files, is there any way to temporarily do this inside my sty? i.e. change the limit only when the package is loaded.

**Comment by davidcarlisle** [comment]
in pdftex you have to change it in a config (or the commandline)  for luatex you can check the value of `texconfig.max_print_line` and complain if it is too small but I don't think you can set it.

**Comment by niruvt** [comment]
Can this be requested as a feature in LuaLaTeX?

**Comment by davidcarlisle** [comment]
well we can't change it in lua *la* tex but you could try requesting it to the luatex developers.

**Comment by niruvt** [comment]
Okay, thanks :)
